name: flutter_shopping_mxl_v2
description: EnOffertaAPP.
publish_to: 'none'
version: 1.0.5+5

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cache:
    path: ./packages/cache
  cloud_firestore: ^4.13.6
  equatable: ^2.0.5
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_local_notifications: ^13.0.0
  formz: ^0.5.0+1
  go_router: ^6.2.0
  google_sign_in: ^6.0.2
  animate_do: ^3.0.2
  qr_flutter: ^4.1.0
  barcode_widget: ^2.0.4
  flutter_launcher_icons: ^0.13.1
  device_info_plus: ^9.1.0
  firebase_storage: ^11.5.6
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.1
  shared_preferences: ^2.2.2
  fluttericon: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
